<<<<<<< HEAD
# p-retry
=======
# p-retry [![Build Status](https://travis-ci.org/sindresorhus/p-retry.svg?branch=master)](https://travis-ci.org/sindresorhus/p-retry)
>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa

> Retry a promise-returning or async function

It does exponential backoff and supports custom retry strategies for failed operations.

<<<<<<< HEAD
=======

>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa
## Install

```
$ npm install p-retry
```

<<<<<<< HEAD
=======

>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa
## Usage

```js
const pRetry = require('p-retry');
const fetch = require('node-fetch');

const run = async () => {
	const response = await fetch('https://sindresorhus.com/unicorn');

	// Abort retrying if the resource doesn't exist
	if (response.status === 404) {
		throw new pRetry.AbortError(response.statusText);
	}

	return response.blob();
};

(async () => {
	console.log(await pRetry(run, {retries: 5}));
})();
```

<<<<<<< HEAD
## API

### pRetry(input, options?)

Returns a `Promise` that is fulfilled when calling `input` returns a fulfilled promise. If calling `input` returns a rejected promise, `input` is called again until the maximum number of retries is reached. It then rejects with the last rejection reason.


Does not retry on most `TypeErrors`, with the exception of network errors. This is done on a best case basis as different browsers have different [messages](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful) to indicate this. See [whatwg/fetch#526 (comment)](https://github.com/whatwg/fetch/issues/526#issuecomment-554604080)


#### input

Type: `Function`

Receives the current attempt number as the first argument and is expected to return a `Promise` or any value.

#### options

Type: `object`

Options are passed to the [`retry`](https://github.com/tim-kos/node-retry#retryoperationoptions) module.

##### onFailedAttempt(error)

Type: `Function`

Callback invoked on each retry. Receives the error thrown by `input` as the first argument with properties `attemptNumber` and `retriesLeft` which indicate the current attempt number and the number of attempts left, respectively.
=======
With the `onFailedAttempt` option:
>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa

```js
const run = async () => {
	const response = await fetch('https://sindresorhus.com/unicorn');

<<<<<<< HEAD
	if (!response.ok) {
=======
	if (response.status !== 200) {
>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa
		throw new Error(response.statusText);
	}

	return response.json();
};

(async () => {
	const result = await pRetry(run, {
		onFailedAttempt: error => {
			console.log(`Attempt ${error.attemptNumber} failed. There are ${error.retriesLeft} retries left.`);
			// 1st request => Attempt 1 failed. There are 4 retries left.
			// 2nd request => Attempt 2 failed. There are 3 retries left.
			// â€¦
		},
		retries: 5
	});

	console.log(result);
})();
```

<<<<<<< HEAD
The `onFailedAttempt` function can return a promise. For example, you can do some async logging:

```js
const pRetry = require('p-retry');
const logger = require('./some-logger');

const run = async () => { â€¦ };

(async () => {
	const result = await pRetry(run, {
		onFailedAttempt: async error => {
			await logger.log(error);
		}
	});
})();
```

If the `onFailedAttempt` function throws, all retries will be aborted and the original promise will reject with the thrown error.

### pRetry.AbortError(message)
### pRetry.AbortError(error)
=======

## API

### pRetry(input, [options])

Returns a `Promise` that is fulfilled when calling `input` returns a fulfilled promise. If calling `input` returns a rejected promise, `input` is called again until the max retries are reached, it then rejects with the last rejection reason.

It doesn't retry on `TypeError` as that's a user error.

#### input

Type: `Function`

Receives the number of attempts as the first argument and is expected to return a `Promise` or any value.

#### options

Type: `Object`

Options are passed to the [`retry`](https://github.com/tim-kos/node-retry#retryoperationoptions) module.

##### onFailedAttempt(error)

Type: `Function`

Callback invoked on each retry. Receives the error thrown by `input` as the first argument with properties `attemptNumber` and `retriesLeft` which indicate the current attempt number and the number of attempts left, respectively.

### pRetry.AbortError(message|error)
>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa

Abort retrying and reject the promise.

### message

Type: `string`

Error message.

### error

Type: `Error`

Custom error.

<<<<<<< HEAD
=======

>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa
## Tip

You can pass arguments to the function being retried by wrapping it in an inline arrow function:

```js
const pRetry = require('p-retry');

const run = async emoji => {
	// â€¦
};

(async () => {
	// Without arguments
	await pRetry(run, {retries: 5});

	// With arguments
	await pRetry(() => run('ðŸ¦„'), {retries: 5});
})();
```

<<<<<<< HEAD
=======

>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa
## Related

- [p-timeout](https://github.com/sindresorhus/p-timeout) - Timeout a promise after a specified amount of time
- [Moreâ€¦](https://github.com/sindresorhus/promise-fun)
<<<<<<< HEAD
=======


## License

MIT Â© [Sindre Sorhus](https://sindresorhus.com)
>>>>>>> 8aded176e2bf64ab331edd712b5a251ef6940ffa
